### ISSUE TITLE
Bundle GeoPHP library

### ISSUE THREAD

**Issue by earthday47** [backdrop-contrib/geofield#11]
Did a fresh install with no extra steps. Added a field and got this error:
Fatal error: Call to undefined function geophp_load() in /code/modules/geofield/geofield.module on line 321

We removed the geoPHP module as a dependency so we can just remove this call. But more broadly, we should include instructions to install the geoPHP library in the documentation as well as a set_`backdrop_set_message` after install as a reminder.

**Comment by jenlampton** [comment]
> we should include instructions to install the geoPHP library in the documentation

For Backdrop sites, there should never be a reason to install a library. All libraries should be bundled into their respective modules.

> We removed the geoPHP module as a dependency...

If we are removing the dependency on the geoPHP module, then I recommend that we bundle the geoPHP library directly into the geocoder module instead.

Everything needs to be installable via the Installer module (so Backdrop itself can act as our package manager). Backdrop end-users shouldn't be expected to know how to install a library, where to find one, what version to use, or even what a library is. 

> Did a fresh install with no extra steps. Added a field and got this error: ...

If the library were bundled, this problem would be prevented by design. No documentation can beat that :)

**Comment by earthday47** [comment]
Merged and in v1.0
